// <auto-generated />
using System;
using Finance.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.DataModel.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20261002123433_AddGruppiMovimenti")]
    partial class AddGruppiMovimenti
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Finance.DataModel.Models.Casello", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Caselli");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Conto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InitialBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Conti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.CorrelazionePianificazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PianificazioneAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PianificazioneBId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PianificazioneBId");

                    b.HasIndex("PianificazioneAId", "PianificazioneBId")
                        .IsUnique();

                    b.ToTable("CorrelazioniPianificazioni");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Finanziamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DueDay")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Fees")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FirstDueDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("InitialPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Installment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Insurance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<decimal>("Tan")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Finanziamenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.GruppoMovimenti", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GruppiMovimenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Movimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContoId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GruppoMovimentiId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Natura")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PianificazioneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("GruppoMovimentiId");

                    b.HasIndex("PianificazioneId");

                    b.HasIndex("ContoId", "Date", "Id");

                    b.ToTable("Movimenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.ParametroConto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContoId", "Name", "Index")
                        .IsUnique();

                    b.ToTable("ParametriConto");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Pedaggio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CaselloEntrataId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CaselloUscitaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovimentoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaselloEntrataId");

                    b.HasIndex("CaselloUscitaId");

                    b.HasIndex("MovimentoId")
                        .IsUnique();

                    b.ToTable("Pedaggi");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Periodicita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FineMese")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequenza")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GiornoMese")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GiornoSettimana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intervallo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeseAnno")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SettimanaMese")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Frequenza", "Intervallo", "GiornoSettimana", "SettimanaMese", "GiornoMese", "MeseAnno", "FineMese")
                        .IsUnique();

                    b.ToTable("Periodicita");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Pianificazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModalitaCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovimentoDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovimentoFormula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MovimentoNatura")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeriodicitaId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoceRicorrenteCategoriaName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContoId");

                    b.HasIndex("PeriodicitaId");

                    b.ToTable("Pianificazioni");
                });

            modelBuilder.Entity("Finance.DataModel.Models.RiallineamentoFinanziamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FinanziamentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Principal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinanziamentoId", "InstallmentNumber")
                        .IsUnique();

                    b.ToTable("RiallineamentiFinanziamenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.TariffaTratta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CaselloAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CaselloBId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaselloBId");

                    b.HasIndex("CaselloAId", "CaselloBId", "Index")
                        .IsUnique();

                    b.ToTable("TariffeTratte");
                });

            modelBuilder.Entity("Finance.DataModel.Models.VoceRicorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Name", "Index")
                        .IsUnique();

                    b.ToTable("VociRicorrenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.CorrelazionePianificazione", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Pianificazione", "PianificazioneA")
                        .WithMany("CorrelazioniComeA")
                        .HasForeignKey("PianificazioneAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.Pianificazione", "PianificazioneB")
                        .WithMany("CorrelazioniComeB")
                        .HasForeignKey("PianificazioneBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PianificazioneA");

                    b.Navigation("PianificazioneB");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Movimento", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Categoria", "Categoria")
                        .WithMany("Movimenti")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Finance.DataModel.Models.Conto", "Conto")
                        .WithMany("Movimenti")
                        .HasForeignKey("ContoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.GruppoMovimenti", "GruppoMovimenti")
                        .WithMany("Movimenti")
                        .HasForeignKey("GruppoMovimentiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Finance.DataModel.Models.Pianificazione", "Pianificazione")
                        .WithMany("Movimenti")
                        .HasForeignKey("PianificazioneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Conto");

                    b.Navigation("GruppoMovimenti");

                    b.Navigation("Pianificazione");
                });

            modelBuilder.Entity("Finance.DataModel.Models.ParametroConto", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Conto", "Conto")
                        .WithMany("Parametri")
                        .HasForeignKey("ContoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conto");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Pedaggio", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Casello", "CaselloEntrata")
                        .WithMany()
                        .HasForeignKey("CaselloEntrataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.Casello", "CaselloUscita")
                        .WithMany()
                        .HasForeignKey("CaselloUscitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.Movimento", "Movimento")
                        .WithOne()
                        .HasForeignKey("Finance.DataModel.Models.Pedaggio", "MovimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaselloEntrata");

                    b.Navigation("CaselloUscita");

                    b.Navigation("Movimento");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Pianificazione", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Categoria", "Categoria")
                        .WithMany("Pianificazioni")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Finance.DataModel.Models.Conto", "Conto")
                        .WithMany()
                        .HasForeignKey("ContoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.Periodicita", "Periodicita")
                        .WithMany("Pianificazioni")
                        .HasForeignKey("PeriodicitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conto");

                    b.Navigation("Periodicita");
                });

            modelBuilder.Entity("Finance.DataModel.Models.RiallineamentoFinanziamento", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Finanziamento", "Finanziamento")
                        .WithMany("Riallineamenti")
                        .HasForeignKey("FinanziamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finanziamento");
                });

            modelBuilder.Entity("Finance.DataModel.Models.TariffaTratta", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Casello", "CaselloA")
                        .WithMany("TariffeComeA")
                        .HasForeignKey("CaselloAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.Casello", "CaselloB")
                        .WithMany("TariffeComeB")
                        .HasForeignKey("CaselloBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaselloA");

                    b.Navigation("CaselloB");
                });

            modelBuilder.Entity("Finance.DataModel.Models.VoceRicorrente", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Categoria", "Categoria")
                        .WithMany("VociRicorrenti")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Casello", b =>
                {
                    b.Navigation("TariffeComeA");

                    b.Navigation("TariffeComeB");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Categoria", b =>
                {
                    b.Navigation("Movimenti");

                    b.Navigation("Pianificazioni");

                    b.Navigation("VociRicorrenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Conto", b =>
                {
                    b.Navigation("Movimenti");

                    b.Navigation("Parametri");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Finanziamento", b =>
                {
                    b.Navigation("Riallineamenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.GruppoMovimenti", b =>
                {
                    b.Navigation("Movimenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Periodicita", b =>
                {
                    b.Navigation("Pianificazioni");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Pianificazione", b =>
                {
                    b.Navigation("CorrelazioniComeA");

                    b.Navigation("CorrelazioniComeB");

                    b.Navigation("Movimenti");
                });
#pragma warning restore 612, 618
        }
    }
}
