// <auto-generated />
using System;
using Finance.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.DataModel.Migrations
{
    [DbContext(typeof(FinanceContext))]
    partial class FinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Finance.DataModel.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Conto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InitialBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Conti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.CorrelazionePianificazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PianificazioneAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PianificazioneBId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PianificazioneBId");

                    b.HasIndex("PianificazioneAId", "PianificazioneBId")
                        .IsUnique();

                    b.ToTable("CorrelazioniPianificazioni");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Movimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContoId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PianificazioneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PianificazioneId");

                    b.HasIndex("ContoId", "Date", "Id");

                    b.ToTable("Movimenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.ParametroConto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContoId", "Name", "Index")
                        .IsUnique();

                    b.ToTable("ParametriConto");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Periodicita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FineMese")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequenza")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GiornoMese")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GiornoSettimana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intervallo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeseAnno")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SettimanaMese")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Frequenza", "Intervallo", "GiornoSettimana", "SettimanaMese", "GiornoMese", "MeseAnno", "FineMese")
                        .IsUnique();

                    b.ToTable("Periodicita");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Pianificazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModalitaCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovimentoDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovimentoFormula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeriodicitaId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoceRicorrenteCategoriaName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContoId");

                    b.HasIndex("PeriodicitaId");

                    b.ToTable("Pianificazioni");
                });

            modelBuilder.Entity("Finance.DataModel.Models.VoceRicorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Name", "Index")
                        .IsUnique();

                    b.ToTable("VociRicorrenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.CorrelazionePianificazione", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Pianificazione", "PianificazioneA")
                        .WithMany("CorrelazioniComeA")
                        .HasForeignKey("PianificazioneAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.Pianificazione", "PianificazioneB")
                        .WithMany("CorrelazioniComeB")
                        .HasForeignKey("PianificazioneBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PianificazioneA");

                    b.Navigation("PianificazioneB");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Movimento", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Categoria", "Categoria")
                        .WithMany("Movimenti")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Finance.DataModel.Models.Conto", "Conto")
                        .WithMany("Movimenti")
                        .HasForeignKey("ContoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.Pianificazione", "Pianificazione")
                        .WithMany("Movimenti")
                        .HasForeignKey("PianificazioneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Conto");

                    b.Navigation("Pianificazione");
                });

            modelBuilder.Entity("Finance.DataModel.Models.ParametroConto", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Conto", "Conto")
                        .WithMany("Parametri")
                        .HasForeignKey("ContoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conto");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Pianificazione", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Categoria", "Categoria")
                        .WithMany("Pianificazioni")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Finance.DataModel.Models.Conto", "Conto")
                        .WithMany()
                        .HasForeignKey("ContoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finance.DataModel.Models.Periodicita", "Periodicita")
                        .WithMany("Pianificazioni")
                        .HasForeignKey("PeriodicitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conto");

                    b.Navigation("Periodicita");
                });

            modelBuilder.Entity("Finance.DataModel.Models.VoceRicorrente", b =>
                {
                    b.HasOne("Finance.DataModel.Models.Categoria", "Categoria")
                        .WithMany("VociRicorrenti")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Categoria", b =>
                {
                    b.Navigation("Movimenti");

                    b.Navigation("Pianificazioni");

                    b.Navigation("VociRicorrenti");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Conto", b =>
                {
                    b.Navigation("Movimenti");

                    b.Navigation("Parametri");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Periodicita", b =>
                {
                    b.Navigation("Pianificazioni");
                });

            modelBuilder.Entity("Finance.DataModel.Models.Pianificazione", b =>
                {
                    b.Navigation("CorrelazioniComeA");

                    b.Navigation("CorrelazioniComeB");

                    b.Navigation("Movimenti");
                });
#pragma warning restore 612, 618
        }
    }
}
