<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\MultiPurposeServer.Shared.Contracts\MultiPurposeServer.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\MultiPurposeServer.Shared.Persistence\MultiPurposeServer.Shared.Persistence.csproj" />
    <ProjectReference Include="..\..\..\Shared\MultiPurposeServer.Shared.Persistence.EntityFramework\MultiPurposeServer.Shared.Persistence.EntityFramework.csproj" />
    <ProjectReference Include="..\Finance.Contracts\Finance.Contracts.csproj" />
    <ProjectReference Include="..\Finance.DataModel\Finance.DataModel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="NCalcSync" Version="7.1.0" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
