import csv,json
from pathlib import Path
R=Path(__file__).parent
D="Canone BNL|Decathlon|Alice Pizza|Le Dolcezze di Liz|Mondo Risparmio|Findomestic|Findomestic|Findomestic|PayPal|Younited|H&M|Bella Recco|Carta principale|Assicurazione|Regalo famiglia Quiroz|Regalo Nelly Osorio|McDonald's|Eurospin|Il Mondo Capovolto|Agos|Assicurazione Casa|Rimborso lista nozze|Marco Cacciapuoti|Spese conto|Bonifico Ericka|Cofidis|Restituzione caparra affitto|Risparmio Casa|Mondo Risparmio|Luce/Gas|Eurospin|Bricocenter|Risparmio Casa|Cart|Rincon Latino|Prelievo matrimonio|Spese bonifico|Bonifico Daniele Mengarelli|Bonifico|Regalo Antonella Laterza|Versamento matrimonio|Carrefour|Assicurazione Auto|Regalo Claudia e Mimmo|Alice Pizza|Mondo Risparmio|Prelievo matrimonio|Regalo Marlene Velasquez|Autolavaggio|Mondo Risparmio|Farmacia Saettone|Prelievo|Bar Milleluci|Farmacia Fascie|Agos|Agos|American Express|PayPal|Regalo Liam|SERS|Mondo Risparmio|Risparmio Casa|Shunfa|Eurospin|AG Cars|Supermercato Royal|Regalo Massimo e Stefania|Fastweb|Polizza Reddito Protetto|Ritiro Folletto|Regalo Centro Servizi Savona|Cofidis|Stipendio".split('|')
C="-|Calcetto|Spesa|Matrimonio|Spesa|Prestiti|Prestiti|Prestiti|-|Prestiti|Abbigliamento|VitaSociale|-|Auto|Matrimonio|Matrimonio|VitaSociale|Spesa|Matrimonio|Prestiti|Casa|Matrimonio|Matrimonio|-|Casa|Prestiti|Casa|Spesa|Spesa|Utenze|Spesa|Casa|Spesa|Spesa|VitaSociale|Matrimonio|-|Matrimonio|-|Matrimonio|Matrimonio|Spesa|Auto|Matrimonio|Spesa|Spesa|Matrimonio|Matrimonio|Auto|Spesa|SaluteBenessere|VitaSociale|VitaSociale|SaluteBenessere|Prestiti|Prestiti|-|-|Matrimonio|Auto|Spesa|Spesa|Casa|Spesa|Auto|Spesa|Matrimonio|Utenze|Polizze|Casa|Matrimonio|Prestiti|Entrate".split('|')
with(R/'raw-movements.csv').open(encoding='utf-8-sig',newline='')as s: rows=[x for x in csv.DictReader(s,delimiter=';')if'2024-05-01'<=x['bookingDate']<'2024-06-01']
assert len(rows)==len(D)==len(C)==73
A=[{'requestId':i,'date':r['bookingDate'],'description':d,'formula':r['amount'].replace('.',','),'categoryName':None if c=='-' else c}for i,(r,d,c)in enumerate(zip(rows,D,C),1)]
(R/'2024-05-approved.json').write_text(json.dumps(A,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
